framework:
    messenger:
        buses:
            messenger.bus.default:
                # disable the default middleware
                default_middleware: true
                
                middleware:
                    # use and configure parts of the default middleware you want
                    -   'add_bus_name_stamp_middleware': [ 'messenger.bus.default' ]
                    
                    # 
                    - 'App\KafkaMiddleware'
        # Create failed transport
        # failure_transport: failed

        transports:
            kafka: 
                # we are pointing to enqueue transport, which in order points to kafka
                dsn: enqueue://default
                options: 
                    queue: 
                        # here we are configuring the Kafka topic that symfony messenger will consume from
                        name: yet_another_topic
                        # We can also specify exactly from which partition the kafka will consume messages (not working, 
                        # we need to optionally figure it out
                        partition: 0

        routing:
#            App\Message\KafkaTestCommand: kafka
            App\Message\KafkaTestOneMessageCommand: kafka
